/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var NAVTREE =
[
  [ "p4est", "index.html", [
    [ "The p4est parallel adaptive mesh refinement library", "index.html", null ],
    [ "Documentation for the point example program", "example_points.html", null ],
    [ "Documentation for selected 2D example programs", "example_simple2.html", null ],
    [ "Documentation for selected 3D example programs", "example_simple3.html", null ],
    [ "Installation", "installing_p4est.html", [
      [ "Installing p4est on Linux Systems", "installing_p4est.html#install", [
        [ "Prerequisites", "installing_p4est.html#prerequisites", null ],
        [ "Optional Components", "installing_p4est.html#optional", null ],
        [ "Step-by-step Guide", "installing_p4est.html#steps", [
          [ "The first step example", "example_simple2.html#autotoc_md0", null ],
          [ "The historic simple example", "example_simple2.html#autotoc_md1", null ],
          [ "The historic simple example", "example_simple3.html#autotoc_md2", null ],
          [ "1. Source Retrieval", "installing_p4est.html#source_retrieval", null ],
          [ "2. Bootstrap Execution", "installing_p4est.html#bootstrap", null ],
          [ "3. Setting up p4est", "installing_p4est.html#setup", null ],
          [ "4. Compiling p4est After configuration, the next step", "installing_p4est.html#compile", null ],
          [ "5. Verification Step It's recommended to execute", "installing_p4est.html#verification", null ],
          [ "6. Autogenerated API Documentation", "installing_p4est.html#api_docs", null ],
          [ "7. Integrating with p4est For projects aiming to", "installing_p4est.html#integration", null ]
        ] ]
      ] ],
      [ "Further information You may also find a detailed", "installing_p4est.html#further", null ]
    ] ],
    [ "Modules", "modules.html", "modules" ],
    [ "Data Structures", "annotated.html", [
      [ "Data Structures", "annotated.html", "annotated_dup" ],
      [ "Data Structure Index", "classes.html", null ],
      [ "Data Fields", "functions.html", [
        [ "All", "functions.html", "functions_dup" ],
        [ "Variables", "functions_vars.html", "functions_vars" ]
      ] ]
    ] ],
    [ "Files", "files.html", [
      [ "File List", "files.html", "files_dup" ],
      [ "Globals", "globals.html", [
        [ "All", "globals.html", "globals_dup" ],
        [ "Functions", "globals_func.html", "globals_func" ],
        [ "Variables", "globals_vars.html", null ],
        [ "Typedefs", "globals_type.html", null ],
        [ "Enumerations", "globals_enum.html", null ],
        [ "Enumerator", "globals_eval.html", null ],
        [ "Macros", "globals_defs.html", null ]
      ] ]
    ] ],
    [ "Examples", "examples.html", "examples" ]
  ] ]
];

var NAVTREEINDEX =
[
"annotated.html",
"p4est__base_8h.html#a86f098e3454f98aedf5298f75cc43d80",
"p4est__connectivity_8h.html#aed57e0d5bcb53770f84510360317352f",
"p6est__extended_8h.html#a3c3366b7ad13c135d0f6c9c7bed8115d",
"p8est__connectivity_8h.html#aaa5a9d47d1b169507e1095783ab89be1a9051491e9a29d4f4978b14b0bc552b62",
"structp4est__connectivity.html#a89a2d05fa39c9174d6b93012be4aa7c2",
"structp6est.html#aec3d1de90d941860b7b396e2a6853809",
"structp8est__mesh__t.html#ac03978ac8da5fffe6d62d1b7c531cd43"
];

var SYNCONMSG = 'click to disable panel synchronisation';
var SYNCOFFMSG = 'click to enable panel synchronisation';